port 26379
sentinel resolve-hostnames yes
sentinel monitor reofmaster redis-master 6379 2
sentinel down-after-milliseconds reofmaster 2000
sentinel failover-timeout reofmaster 5000
sentinel parallel-syncs reofmaster 1
