port 26379
sentinel resolve-hostnames yes
sentinel monitor craftmaster redis-master 6379 2
sentinel down-after-milliseconds craftmaster 2000
sentinel failover-timeout craftmaster 5000
sentinel parallel-syncs craftmaster 1
